### ISSUE TITLE
Tolerances

### ISSUE THREAD

**Issue by biuti** [kuaka/airscore#9]
I am thinking about implementing tolerances.
Let me know if you agree:
with tolerances > 0, every kind of waypoint a part from goal line and t/o is true if
radius -tolerance < coord < radius + tolerance
This should be true, isn't it?

**Comment by kuaka** [comment]
look in Route.pm for margin, there is 0.5% (as per PWC) tolerance on cylinders. Is this what you mean?

**Comment by kuaka** [comment]
So perhaps we should:
Create two new "Advanced" scoring parameters. "Cylinder tolerance" (%) and "minimum Cylinder tolerance" in meters. 
Must also remember to add any aditional database fields to the DB setup (xcdb.sql)

I believe that Route.pm has tolerance as Max of 0.5% or 5meters. Which is a Civil GAP and not PWCA. 

PWCA rules 2016 just has 0.5% tolerance, no minimum (so MAX(0.5%,0). 
While CIVIL GAP 2015 (maybe it has changed since?) uses a mimimum of 5 meters or a percentage (0.1% or 0.5% but in reality I think it can be defined by comp organisers)  (so MAX(0.X%,5).

PWCA rules (2016 section 14.5):
_4. A tolerance of 0.5% is applied to all cylinder radii to deal with different formulas
used in GPS receivers and computer software to calculate distances.
Example: On a 400m cylinder, this gives a 2 m tolerance._


CIVL GAP 2015 section 8.1.1:
_Starting January 1st, 2015 – provided all distance measurements are then based on the WGS84 ellipsoid
(see 4.2) – the tolerance for turnpoint cylinders in CIVL’s FAI Category 1 events will be reduced to 0.01%
of the cylinder radius, with a minimum of 5 meter. Organisers of FAI Category 2 events may continue
using the existing 0.5% tolerance, to accommodate pilots flying with instruments which calculate
distance based on the FAI sphere._

**Comment by biuti** [comment]
Agreed.
I will look into this today
Surely tolerances has priority. I will try to add these parameters to the scoring formulas table, falling back to max(5, 0.5%) if not specified.
At least in the beginning could be safe to leave a minimum of 5 meters as distance calculations are not consistent.

**Comment by biuti** [comment]
I have added a parameter "margin" as radius tolerance in tblFormula.
It's used now in calculations, with fallback to 5meters as minimum.
Did a little simulation and seems to work, more debug needed I guess.
I'll try to visualize tolerances in track map

**Comment by biuti** [comment]
I added tolerances circles in tracklog map.

**Comment by biuti** [comment]
![margin](https://user-images.githubusercontent.com/35658597/35765529-9e88e130-08c5-11e8-8ef2-09545e53b189.png)

**Comment by biuti** [comment]
Added markers for each point, visible only when zooming in the track (over zoom factor 16)
On mouseover the markers there's an inbox with position, UTC time and altitude
![marker 2](https://user-images.githubusercontent.com/35658597/35770124-c82ce0e0-0915-11e8-8f93-fb5583733704.png)

**Comment by kuaka** [comment]
I think we can close this.
